# Generated by Django 4.0.1 on 2022-01-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registration',
            new_name='Internshipregistration',
        ),
    ]
