# Generated by Django 4.0.1 on 2022-01-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_rename_registration_internshipregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipregistration',
            old_name='branch',
            new_name='collegename',
        ),
        migrations.RenameField(
            model_name='internshipregistration',
            old_name='designation',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='internshipregistration',
            name='emp_name',
        ),
    ]
