# Generated by Django 4.0.1 on 2022-01-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_rename_branch_internshipregistration_collegename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipregistration',
            name='end_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='start_date',
            field=models.DateField(max_length=200),
        ),
    ]
