# Generated by Django 4.0.1 on 2022-01-21 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_alter_internshipregistration_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipregistration',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
