# Generated by Django 4.0.1 on 2022-01-21 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_rename_currentdate_internshipregistration_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipregistration',
            name='guide',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipregistration',
            name='hrmanager',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipregistration',
            name='rating',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
