# Generated by Django 4.0.1 on 2022-01-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_internshipregistration_guide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaveform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('no_of_days', models.CharField(max_length=200)),
                ('leavefrom', models.DateField(max_length=200)),
                ('leaveto', models.DateField(max_length=200)),
                ('halforfull', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('delete', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='attach_file',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
