# Generated by Django 4.0.1 on 2022-01-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_leaveform_alter_internshipregistration_attach_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='delete',
        ),
    ]
