# Generated by Django 4.0.1 on 2022-01-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_remove_leaveform_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='no_of_days',
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='attach_file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='end_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='start_date',
            field=models.CharField(max_length=200),
        ),
    ]
