# Generated by Django 4.0.1 on 2022-01-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_remove_leaveform_no_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='leavefrom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='leaveto',
            field=models.CharField(max_length=200),
        ),
    ]
