# Generated by Django 4.0.1 on 2022-01-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_alter_leaveform_leavefrom_alter_leaveform_leaveto'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipregistration',
            name='qr',
            field=models.CharField(default='', max_length=200),
        ),
    ]
